/**
 * Jest global setup — mock @prisma/client enums so tests can run
 * without running `prisma generate` (which fails due to a schema bug).
 * In production, these enums are generated by Prisma. For testing,
 * we provide string-enum equivalents.
 */
jest.mock('@prisma/client', () => ({
  // Enum: HealthRecordType
  HealthRecordType: {
    VACCINE: 'VACCINE',
    DEWORMING: 'DEWORMING',
    CHECKUP: 'CHECKUP',
    VISIT: 'VISIT',
  },
  // Enum: ReminderType
  ReminderType: {
    VACCINE: 'VACCINE',
    DEWORMING: 'DEWORMING',
    CHECKUP: 'CHECKUP',
  },
  // Enum: ReminderStatus
  ReminderStatus: {
    PENDING: 'PENDING',
    NOTIFIED: 'NOTIFIED',
    OVERDUE: 'OVERDUE',
    DONE: 'DONE',
  },
  // Enum: PostStatus (used by communityService)
  PostStatus: {
    PUBLISHED: 'PUBLISHED',
    DRAFT: 'DRAFT',
    ARCHIVED: 'ARCHIVED',
  },
  // Enum: CircleRole
  CircleRole: {
    OWNER: 'OWNER',
    MEMBER: 'MEMBER',
  },
  // Enum: FollowStatus
  FollowStatus: {
    ACTIVE: 'ACTIVE',
    MUTED: 'MUTED',
  },
  // Enum: NotificationType
  NotificationType: {
    REMINDER: 'REMINDER',
    SYSTEM: 'SYSTEM',
    COMMUNITY: 'COMMUNITY',
  },
  // PrismaClient constructor (mocked)
  PrismaClient: jest.fn(() => ({})),
}));
